### ISSUE TITLE
service won't start on ubuntu 16.04

### ISSUE THREAD

**Issue by adespain** [singleplatform-eng/ansible-role-awslogs#2]
I noticed I had to enable the service first with systemctl entable awslogs and then it produced this error:

systemd[1]: awslogs.service: Main process exited, code=exited, status=255/n/a

Any ideas on why it's not starting?

**Comment by ghost** [comment]
@adespain The travis builds [appear to be passing](https://travis-ci.org/singleplatform-eng/ansible-role-awslogs/jobs/225778096) idempotence checks and I just verified that the service starts as expected on a clean ubuntu/xenial64 vagrant VM. Can you provide a little more information about the environment that is executing this role?

**Comment by ghost** [comment]
Closing this, let me know if you continue to have issues.
